services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: levon
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: airflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  airflow:
    build: .
    container_name: airflow
    depends_on:
      - postgres
      - mongo
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://levon:12345@postgres:5432/airflow_db
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
    command: bash /opt/airflow/scripts/start_airflow.sh

volumes:
  postgres_data:
  mongo_data: